### PR TITLE
add quote sources

### PR DESCRIPTION
**Pull request by elen-mou**
This PR adds:

the source of the quotes provided.

### CODE REVIEW

**Comment by threadexio** [comment]
Great PR!

Note that the code that parses the `src/quotes.txt` file:

https://github.com/threadexio/cbundl/blob/6a080153ff340c37283adeffbdfe1f2cbb165b1e/build.rs#L90-L144

Does no filtering of the `author` field (the part after `|` for each line of `src/quotes.txt`), this means the characters `<` and `>` will be included in the output.

For example, assume that `src/quotes.txt` contained:

```
Quote text | <John Doe>
```

The tool would then output:

```
/*
...
 *
 * Quote text
 *   - <John Doe>
 *
 */
```

I am pointing this out because I only added the `<` and `>` to signal that it was a placeholder. Anything after the separator `|` will be printed as-is in the output.

Are you sure you want to include the `<` and `>`?

**Comment by elen-mou** [comment]
You're right to have pointed this out. In that case, the the `<` and `>` are unnecessary. Thank you in advance!

**Comment by elen-mou** [comment]
Fixed the issue and added some more quotes and their respective soruces. Should be okay now.

**Review by threadexio — APPROVED** [review]
Looks good! Merging now. :+1:

**Pull request merged**
