### PR TITLE
Add Minify Option

### PR DESCRIPTION
**Pull request by mgiannopoulos24**
### Description:

This PR introduces the `Minify` option, designed to optimize and obfuscate (partially) source code by applying three transformations:

- **Remove Comments:** Strips both single-line (`//...`) and block comments (`/*...*/`).
- **Remove Whitespace:** Removes unnecessary whitespace and empty lines.
- **Shorten Identifiers:** Replaces variable and function names with shorter identifiers (e.g., `v1`,` v2`, etc.).

These changes aim to minimize source code size, making it suitable for specific applications like obfuscation or code compression.

### Usage: 
To apply the minification transformations, run the following command:
```
cargo run -- source_file.c -o output_file.c --shorten-identifiers --remove-whitespace --remove-comments
```

### Example:
```
cargo run -- test/minify/unminified.c -o test/minify/clean.c --shorten-identifiers --remove-whitespace --remove-comments
```
#### Before Minification:
```c
#include <stdio.h>          // Include standard input/output library

    // Main function, entry point of the program
    int main()             

    {                       // Start of the main function

        // Declare integer variable x and initialize it
        int x = 5;           // Variable 'x' is set to 5

        
        // Print the value of x to the console
        printf("Value of x: %d\n", x);  

        
        // Another dummy comment with no real purpose
        // Just filling space to make the code look bigger

            // Adding more unnecessary whitespace for no reason
            for (int i = 0; i < 3; i++)     // Loop to run 3 times
            {

                // Print a message in the loop
                printf("This is loop iteration: %d\n", i);

                
                // Another pointless comment
                // Just taking up space

            }   // End of for loop

        
        // Final comment that does nothing
        return 0;           // Return 0 to indicate successful completion

    }                       // End of main function
```

#### After minification:
```c
/**
 *
 *                        )                (    (
 *                    ( /(    (           )\ ) )\
 *                (   )\())  ))\   (     (()/(((_)
 *                 )\ ((_)\  /((_)  )\ )   ((_))_
 *               ((_)| |(_)(_))(  _(_/(   _| || |
 *              / _| | '_ \| || || ' \))/ _` || |
 *              \__| |_.__/ \_,_||_||_| \__,_||_|
 *
 *                cbundl 0.1.2-debug (f260339+)
 *             https://github.com/threadexio/cbundl
 *
 *      Generated at: Thu 26 Dec 2024 18:37:28 (UTC+02:00)
 *
 *
 * You'd think the rain would've cooled things down.
 * All it did was make the heat wet.
 *   - Rear Window
 *
 */

/**
 * bundled from "unminified.c"
 */

#include <stdio.h>
int main() {
  int v1 = 5;
  printf("Value of x: %d\n", v1);
  for (int v3 = 0; v3 < 3; v3++) {
    printf("This is loop iteration: %d\n", v3);
  }
  return 0;
}
```
### Future Tasks
- We may need to fix the way the program parses the C files.
---
Let me know if you'd like any further adjustments!

### CODE REVIEW

**Comment by threadexio** [comment]
Interesting idea to add a minification option!

My original intention for this tool was to create relatively human-readable bundles. This is because I use this tool to bundle my code together for university assignments because they don't allow build scripts, `Makefile`s, etc.

However, I think we need to reevaluate why a minifier is even needed in the first place. The first example that comes to my mind is javascript. In javascript you have things like `webpack` that do minification and bundling, as far as I'm aware. This "hack" is needed in javascript because the code is shipped directly to the browser over a relatively slow internet connection. Not minifying javascript code means sending the extra spacing, comments, etc over that slow internet connection. This directly impacts the load times for the website. It makes a big difference.

But in C, we don't have this problem, all code stays on the developer's machine and is only shipped in a binary form. In this binary form, both minified and unminified code produce the exact same binary (assuming a deterministic compiler). So I don't really see any real benefit in doing this minification.

Even still, this minification process might even degrade development experience and result in stranger bugs that are hard to find. Assume that you have code that uses `__FUNCTION__` to do some debug printing. If this tool goes and changes the function name to something completely different, you have to search through minified C code to find exactly which function that is.

In any case, this PR outputs invalid bundles. Running the example in `test/frob/main.c` we can see that `foo.h` is added to the resulting bundle twice, once before the banner and once in its proper position. Also `-o` is broken.

I am also skeptical about the whole regex stuff. It seems like a write-once hack to avoid having to include a C parser. In the tool we deliberately avoid doing too much preprocessing of the actual C code because:

1. that is the job of the preprocessor and the compiler
2. that means we have to include a full C parser (and that comes with its own headaches)

Doing regex matching on source code, I think, is just creating problems for later. You caught all of the possible cases, until you didn't.

**Comment by mgiannopoulos24** [comment]
Alright then. I will remove the `shorten_identifiers` option only because I believe the other 2 are useful. Are you okay with that or should I just close the PR?

**Comment by threadexio** [comment]
> In any case, this PR outputs invalid bundles. Running the example in `test/frob/main.c` we can see that `foo.h` is added to the resulting bundle twice, once before the banner and once in its proper position. Also `-o` is broken.

As I mentioned, the PR breaks everything. I cannot merge it until these issues are resolved.

> I believe the other 2 are useful.

I don't really share the same view. Given the issues I raised in https://github.com/threadexio/cbundl/pull/2#issuecomment-2563609653, how are they useful?

**Comment by mgiannopoulos24** [comment]
Okay then. I will close it and come up with some other idea.

**Pull request closed without merging**
